{
	"data": "ENC[AES256_GCM,data:izAiK7YJOshRM/THlmTxY4umg8M3EVnpnDaR2/kI1NVI4sWNZgErw5OGpger+rLOEPPWzu5OqppeQPIvOJkpetlg+IYUCA==,iv:KVV9LtssRZvNZ3AFKTANXrUndyK0uZAz/jf6ExrSozw=,tag:X5b1Ngno7NhSwJtW4cbI/w==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1cnktwwj4lq4lm5qa3vxn2ft5n38h557smr2f58t9vz4zum5w0udqzzle6c",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLWE85cnpDY1ZTb2xhN3Zp\nbGxMeDAyUktEQit1V1FqVFZSamlPT2VsbVZFCkpkZHBFYlNZOFc0MHk4VlkrT28w\nNzRiV0hPQnMxRExhSFRhNUVLaU1pWUUKLS0tIFV0N0cvMGtpU1liOEpHd1FXZk9J\nOFZ0eGZrL2grSzFIbHpJTTY3MExwbVUKufd1YfI3O+8XJGhL4QpZXaMBgij9FkBn\nfIuqcgRxGnyjkulubo+7NpsFQ14Rb+hV8C/DUniCRSfX9XnyTzXULA==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-04-18T02:24:33Z",
		"mac": "ENC[AES256_GCM,data:gH1TQGRFeyGzDpY845Vtj6TKkqPpf8ixEse+2zhlrqDb1CzxVz8hg/rB0aG7eW2qzNm2tWIhXF0K0ojbAN2fkepISLgnivFI6yIcYVcvrMWoOc1lS/MhHSYQd01+eG2Lcmjpi73EcidhMP7cmgjzMShN4DNUGth1bUTwtgZIK0M=,iv:YXLRF3D0TrnngkxolSPUcEbB0zVcmfoDE5C0Mbl8W9w=,tag:DLVhDRtziupn8mwbuB9LZQ==,type:str]",
		"version": "3.12.1"
	}
}