{
	"data": "ENC[AES256_GCM,data:nsWDxDvgon3bmbo/IPVQi+QG+6DeZbS5n5smnCQJK4wnt6ZO3Q43/NPwY/69XIw/SVAVisGHaHi4LlobW8TWAZXEFLrLAg==,iv:VSw6ojS48H+xzpfN1v7DWngd1YjTleTPbFpcL6vyJbs=,tag:qID2IlUkV5SISCaf2qCalw==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1cnktwwj4lq4lm5qa3vxn2ft5n38h557smr2f58t9vz4zum5w0udqzzle6c",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZGZWWkM2TGU4SzJoS0Zo\nNUkwUmc3aG1DOWFTaWs0YXJhZlhFL0xHQUFJClVXQ2w2Rlpha3kzSDdKMDRHbmoz\nTHA2SXV5QVFkQUlkREEzSWhpOFNLdEUKLS0tIEhsWFU0RUNBRndXaXV2U1lsakFu\neldPVDQvYjA1bzEwYllkNWhQK3U5anMKpQeA0lF/F3Yu5dePyW22zUAEp1A2Dvt9\njA8BRS1mR+K0Odkvuack9xZaUGhBNnfCUSOY+7jtC53Dk0WjnWvSDg==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-04-17T13:46:16Z",
		"mac": "ENC[AES256_GCM,data:zMbLkhGf4w+DD8v+wOjAukdPE0oi3U93ZAB9v9nCtkMKOCL5jL3/uRI/hfJIWFGJ/ZkCD7jhM052LXTR/sWQa8+G5Gr/RJlmkBfiLZyI4fJTG7ATanBAoFagh0mGSXIGqMheCupznqHO/7irrRiiHqVN9cfOv5CmPWpiQx9qI20=,iv:cum47U/3Gh7IfEEdlX+pbfrguIockM5vevWQgS3PAcQ=,tag:uzUB1d8ULjy7y6bfnLV+0g==,type:str]",
		"version": "3.12.1"
	}
}