{
	"data": "ENC[AES256_GCM,data:L5QoIUFyNAkr/rIiSPPNUdFRvrTC7M2GCtbalVmKFfWIr3s48WBkXGRd2b+ZOUKIAiXTt0fgdPDKcegx+wkaKOynChP5Rka1rGs5mnNtnhq1MrBDGa6FT49O1p0mADgcK4g30cvpSW4xwcrzqcjqA6vvEzS7yUVUyVoNBH32lRacnWZRIhE0aIu1JXOa9oVWTwcFj0niWGXtBc2zHev1p8wqMPojPyKPwpWydXbPEQaXEfqQuBN6luj9OrPJSLZ2ivKaXzpGILOq+LT8Wp9V4RQxSYB40Sg=,iv:nvSjsyInJ8mfydfRCo3Ik6O1pMZBtrer8nu6JED8JoU=,tag:pkZh+FxhT9b5p24p//XIDQ==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1cnktwwj4lq4lm5qa3vxn2ft5n38h557smr2f58t9vz4zum5w0udqzzle6c",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2SGpvck13Y0UzMGNsRkxD\nY0hvMm9VOE5pdWRERlBqQitzeENBZ3NSYVhFCnZ2S3V0aXpyUGsyZTNHVnNPVklr\nZER4MzkxeHBEM0xYNnd2eVhKNjdRSVEKLS0tIEgyTnhzQXA5elhmUXRneDlQQ1Y2\nTDd4dzRpV0dhcVprV3hkb0g1QlBkdE0KWWtFFmX0ze4UsqrtTjKq7gcWZlQi9FPA\nPBOcrzfRuNz9w35Dm0BXemP/FPwVyOaK8muycVSkf52rX/K5JdIA8Q==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-04-18T02:24:32Z",
		"mac": "ENC[AES256_GCM,data:CYN9p2rR/zMLu/DyTy8y/k7sw2T5kMs4p4rO6TTIebERopcWXLJvgJvE0w2YlwppgN5XF4axGxuuTank8xLfLKdrVWAyhMlKrgd0U4rPC1JNSLK6HoiZE6lQuCtImg3wQKJt/MXxoXjV8QivVDM8Mw9QKUkTiYSGSMQ0xQZ34OQ=,iv:1OQtqbJxairA2BmwfvGMXAQ4lCrNnV4T6iZPEwxqG2o=,tag:wjvwZz9LxjSu345K9ofEag==,type:str]",
		"version": "3.12.1"
	}
}