{
	"data": "ENC[AES256_GCM,data:/hpgY2G/2KIC1lzl0X7o/D/VDXZsz6tP2sKfHPQb4EgSMTyp7sh+Hv99cDAQdS7sLJhAFxjtnTN95VVNXgibftj8OaEm5fysCV9yAlzISlWmsex+55c9djqbyX2/2GClLLTjsg8PVbvf9B/LQoA2oab6moslBYGbE00f43RQiuJS8RNplFWV8YC1TRwtb5GIx5X/IZAOXbKBlK7mTrht2UStoxaobMKWMwHCti9iXGXIpZPJndEYliOpIiSYLli3x67RyPUFXfh0ncVAoj24XDo3Q9Fe/5k=,iv:hEfu5tIOcGmTBZgHocyxwMGZSajnZBrsePPpbtSOXrU=,tag:231Ky6oaVcCur78Oyi9jnQ==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1cnktwwj4lq4lm5qa3vxn2ft5n38h557smr2f58t9vz4zum5w0udqzzle6c",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4aGY0RUJzZFJkd3hOUUtK\nVG1qb0lna0lLc0lOdERvdFR5cXdxZENhbnpFCjBnYjJrZkdqeFovdzY2L3pxZVZ3\nVkEzVVBzRzZRdDl1NEpqRGt5VVJVY00KLS0tIDhvNXRENlFaUk9ad2JiYS9vNWhq\nWlNRby9sNUlGVTRRcUpZOUo4Z0JDYTQKJB3RfQAnATIxu96Etv0ODjXUSplcCHNt\n7PWhd36y9Je97f3OannVw0twvyZuNoWpSvZdtWbwRq1njNwBW3yQ5w==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-04-17T13:16:14Z",
		"mac": "ENC[AES256_GCM,data:J4cSRvoHDA97nFEsar2qAlaWTDFz5s/7hdoo8b7vjS93fEMyG5CVkjbnELHhcWU9s2pfigEwFYPE8YLVuOu4UUlxHGz1OcKbPJficLXyItBL46xyu96DIvmqtrYqYSMGW5i/MwSnXBaL5s/miETksbL+AHUjoNaKPHSEopsgzzc=,iv:wzt/jJPc6FKgVHG7PpINOnO6VUV+kZxOpDBEa8W+LcQ=,tag:BHU3uOh6E5xHuCNikBJiCw==,type:str]",
		"version": "3.12.1"
	}
}