headerStyle: ENC[AES256_GCM,data:+4QZ6nA=,iv:2bCyk4SXvvKX+ze0LH0FwTnotyzFzAwq3JPZkX3PfeY=,tag:jXqPZUFHm7ftk2cGGn7Tvw==,type:str]
title: ENC[AES256_GCM,data:YTBWKjMmcVU=,iv:MP3+KUywR9UyOtCDxAB7SKEI5Fd5KuQwILVYavLpeUk=,tag:IXOTlydB6R2yXnaVipgQ5Q==,type:str]
layout:
    Media:
        columns: ENC[AES256_GCM,data:9w==,iv:NQLG6abS5g8vzsdkr8BE4N2PIM11snrY7tYchMdi55c=,tag:bpY0Akd4NlPBdwg1OHI7FA==,type:int]
        style: ENC[AES256_GCM,data:9bCe,iv:Wy9lAZ1mBAJ6OUzlmGDKnGHYZX87sW6j6ReDuUfHSq8=,tag:fg3jMR+u0boXT8v0kvDB1w==,type:str]
    Productivity:
        columns: ENC[AES256_GCM,data:1Q==,iv:QIiXY9EVQ61x8gb35lg2XcRwv5rWZAzlmhqk23quHLg=,tag:jXKVEjKsBV/H0MGmWmR9pQ==,type:int]
        style: ENC[AES256_GCM,data:FTnw,iv:zgNE4TRzc9p8Cf5j+BX1iuDHhrdXzmc/kP+xXiCYf/Y=,tag:rfYj0gNstsljkMiCoWT1UQ==,type:str]
    Security:
        columns: ENC[AES256_GCM,data:8g==,iv:38ZX2SziJCbgEaqsMckiYWBcdOLw/n04zLOxlqWfemc=,tag:ZX64xaRkVf85LZ2WJmru+A==,type:int]
        style: ENC[AES256_GCM,data:jeZf,iv:E69K1Gn5QQBFVC+y8vowE1YbThE+Udcc9cAPYa3SQOk=,tag:vpeyiMWCWPIqp++ufj3YFA==,type:str]
    System:
        columns: ENC[AES256_GCM,data:zg==,iv:uCNUOpy+nm8ngvZgU445Vc6gqjP5TyIz92Lkx92wQtU=,tag:owmQQkjJRt2bOE0wuo1J+Q==,type:int]
        style: ENC[AES256_GCM,data:ix5+,iv:0pPUvsVrADW885ggmI1y/EwsKP4Z07cenJoFIY6gdKk=,tag:dAug2H8dE3WGRdynGd0v9Q==,type:str]
sops:
    age:
        - recipient: age1cnktwwj4lq4lm5qa3vxn2ft5n38h557smr2f58t9vz4zum5w0udqzzle6c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnRzI0NFZNcUtIUnoyMWNp
            T3dzZVZJWjBvdjQzdGZtN2pkT0lpZWV1SFdFCkcwemRCaVRqOVNwdGxqVkc5VDR5
            RjVtSzE4WTlxU1FTYlR2dlgrdkxNUEUKLS0tIDNUM05aWTY2TmMyWmd6SnorMUpD
            OSt5blJXSnpzUW9zL25nK0Ira3BkODAK0XHF5OWTvpPgNMU9uPaCsmFmK4nIXMld
            RwAMCWQggd50LreByt8UN8pvgHz4Fv9wjRnGpAB9AdCPPKMg2oec6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-17T13:46:16Z"
    mac: ENC[AES256_GCM,data:05TpyODtkRWaab5ELBb2XXTo82Y2Bs/cq3VZkyOSnd3CmpzOcOpjSO8wj5jwCTRtXHWgxT84hh9M2i8jDdQRcD2n6DppcSO0mqpTHeJE8dCU54M8F8X9EZvqVCtfKrRimAee0/t4gZqwBBc+hcZaeV2SlcVOP5v0JCb36NqemQY=,iv:vsGGORnGHp8s13gAL5+uAMSZT3WsqHPo7IUAkJQ/VtQ=,tag:RM9xXN088SwY0LlSiRBa5A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1