headerStyle: ENC[AES256_GCM,data:A1dQRQM=,iv:lxOFbMDIwBObD+0kMSo0tec+i0tnXZitJrUwYr9YkWE=,tag:OEhOSqGldnkItFKtJ62a1Q==,type:str]
title: ENC[AES256_GCM,data:fYW6RTzCjIU=,iv:SZKXGbNglerj0mSq1FVjitn6vaAafMK8AgUnNKDDlJQ=,tag:Og+AV1ASdX2bysri/9HlLA==,type:str]
layout:
    Media:
        columns: ENC[AES256_GCM,data:uA==,iv:MO3q18/X8GfmXzg3OXEBRQ26q5KqfH6LKHNS+61aBBU=,tag:rxFnl/drjQNErrk8WNxkFg==,type:int]
        style: ENC[AES256_GCM,data:wDcw,iv:xVqKvksZtxkwl9T6UYSpn7NB5mI2QEZ69d+vRj3b5wM=,tag:pbAzc5TI7PwJmOozhk3PaA==,type:str]
    Productivity:
        columns: ENC[AES256_GCM,data:0Q==,iv:rDcvU58IVQSuxvg2g6hy+GVIiWDm1eObMWPAaFCfbi8=,tag:jKyEMTRkgfvRqoSRRKzbhg==,type:int]
        style: ENC[AES256_GCM,data:LGX4,iv:cNVdGpZIdpuJNI789St+99lz1a0GsX4Q8PlIWZgByx0=,tag:W2cyR5knT/ZddXCKkrWhXA==,type:str]
    Security:
        columns: ENC[AES256_GCM,data:Fg==,iv:ZZlRsAQnrymGPIaHefR5Y3qG5EbjLVWwFWTlLHRIVoI=,tag:tHLfqzoCyHTeDqfwXysc4g==,type:int]
        style: ENC[AES256_GCM,data:bWvy,iv:ixgCDfLj4HF5r6STdVPZWtnuBmLpRVj7e9EiRVAb62Y=,tag:BeNgnlkkUz8afWPpTxEKDA==,type:str]
    System:
        columns: ENC[AES256_GCM,data:ig==,iv:wwhIsaZQoA01l1nJzIIV5HCygtmSmSa3FP4bFJOi07g=,tag:i0xAiHhSLoYdX5isB+NuFw==,type:int]
        style: ENC[AES256_GCM,data:ecMy,iv:QztV4IG2NEU3+oeUxcWXQxqkHGVXJht3gsJ39sc8lnQ=,tag:4t+JwiLecPhqfN3ASnSDog==,type:str]
sops:
    age:
        - recipient: age1cnktwwj4lq4lm5qa3vxn2ft5n38h557smr2f58t9vz4zum5w0udqzzle6c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzaXVCbE5IQ1JDOHRNc3dX
            bWdST1dCS3lRV0svZUFDZyttRmV3VVpCNm5jCnNXUm1rdjhXdnlJcWt2RC9mUXVy
            c1llMzdtREFSTXVDUFJoUTFkeENxTDQKLS0tIHpRWUdlbktzUWdwY3lwOCtUWGN5
            cEREZDVFMVJQMjBPS1pCY2JXb2YxZVUKDSeGai6FWw6tXXK4nvHf3uFCHzNc0OGw
            YJ5bOq0Ew6yOgaet7p8r6Qf2041VKdQHqGZz/KoIcXOvtW9KimyN0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T02:24:33Z"
    mac: ENC[AES256_GCM,data:VDaaXoBvWC7wch07a+M7C8oagguqTKhVXWjB0yIAdGqroeIVIvG37zvDyu6osJ0Bz2mt8u2ORVTxcut9BfiLlr2TNzyKLy/djoA63Bpv08wOSnxlAOkC7GwKyK4z1G6inA88+AmE3XtlRzqkvIEYciOVnwDqs3OQad8xp5cprC8=,iv:/CI96lckIPSlNIpXyECQG+3VQZizO+5xqPqi+6ci9Lg=,tag:KGlQIBvDjXq4LMYLkNk8zg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1