{
	"data": "ENC[AES256_GCM,data:39YAB1zNb7EALgmy1p4jehEX+abeJq1ntMyl6acxqino6OTOXDkFk/Y5dFjn4YT4kZcC5T4871k0vpEl0eQMCTInhEEGHnzWNgKP1MlElojs9UPY65sWNCZDVckmKeUpRZcPRFXvMOzrv6vJrPYLWotG1WBU+2QyfX0wxaeIjRMt5dGjuTfo05Pdr93mcfMGruVv8fiiZwuGkeqgploO52TPHnOAne0Wx3PB2Na1I/+v3BZc9GI7yhKy,iv:Fe2RPP8zGg6IHEBq94vPDNyT/mJkcMpsOpqerecjOfg=,tag:ocoFstrPUF9Tg53oZRN5Og==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1cnktwwj4lq4lm5qa3vxn2ft5n38h557smr2f58t9vz4zum5w0udqzzle6c",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtSG5hZHY0dmtobi9VYzhi\nTXpPUW9GY0wvbTF6TjBrRnkyaDkzMG82dVNRCmFrQmFiQ3o3aXlpWnZrNlBwaS9o\nRmNRR3AwOExVSVZ5NjIrQy90SkFLeHcKLS0tIFk4bDVabWx2VEc5dnJ0cmZlMUs5\ndFBVTkIzNjU1VHBXZU4yQmxPRWo2ZXMKXD+NpW9esqCU/AkdkF3EvRQSeMl0fJ2P\nn6+1HzXGz9AqhuZ2cDI3+AU8nnoTK1n59VVOc0ntyJtXu/DhP8qq8Q==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-04-16T03:34:26Z",
		"mac": "ENC[AES256_GCM,data:VsoYFQFUs408HNYwzP6bHceUPnknoYXZGwYIK623wZRdk2ucD7GGgF4/Yi5Nq7j/jBTjtmMHJgst0U/SV/AWrjTo76m5JIpZUUsbL50kujUdos1YJp17ZAmf6aqwkKd1Jw+rFHjIAQotNwc3VyfY/ka9kSGcyyVokxz54RNRnV0=,iv:vTad8K/wRWjGlTsbIg6EmR2wJeHVdIopUCV29COnjbc=,tag:96GNJUzHAugh5ujzzAvBBw==,type:str]",
		"version": "3.12.1"
	}
}