{
	"data": "ENC[AES256_GCM,data:kLjkCi8wNG1LazatkxPV+ey0YmWFUXjMh3Sd7fSuKEQSxdYLCyPGtF3bSt63ZtGdG58n9EGragic8JnJ5LiB2qhPxrsjBiMHXZfApI2k5f5UHEjhThht4Iq+tOl7VOqtpix43m7PwPxk+opTzL+tG6mTSxuGzd1bL5Gb9Zd0s14KaRtwwsU/WJ5kRg1/oshKCF61oq/3YeFftnjqaO062n6KlgfkaphSEaHIvT6wytys1Z/oRX9e8uaNowCbRg==,iv:pfTGztIH8LXeBeGUF7YLjYvI8OKWWtcOdISs+sUPIi8=,tag:7kJs6lTH0g9av4SzGL6DxQ==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1cnktwwj4lq4lm5qa3vxn2ft5n38h557smr2f58t9vz4zum5w0udqzzle6c",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwWU4yV2swNWQ2NGZXRy9m\nNzRJaU9XMEkrMW4reWJxWXpOaDM3OHpxWjIwCmlQWmxuT1RickZVbC9yVVk5SVpr\nVU1hQ091RlFiSTRrbzdBQ1ZTMGlQNUUKLS0tIGtZT2gxNjdkRmp4bWZsTEthMWxP\nSDRzbzh1TVRIY2VSSG94WXBETFVlbVkKJCT2mTK/ZcYFJP7y1zTlW76WtxN0qd+h\n0g3O29RNaLMzAtAlZY4MVCHV+gqRM/3am+Lnd4yqbsTTk/ADYfUSvw==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-04-16T03:58:51Z",
		"mac": "ENC[AES256_GCM,data:DFMlGYoyqzmwtYGy6Jqc02d2wP8RzkpvtV8L9Mu9Euu474sTAusrwMZ1YKxKx9fQm+LV6Y3Qr5V5HrgbK0NIfV/KBfNvV6pcKPt/TpKF0a4ezP8uRFYYiNb+xwbhzoSrvMa00ZcV6EApxd1lqlXrs1l3CPva5D4sa2RvPg71CYA=,iv:TLtJQcCZwaDk18b/HJRPTQzEo39AFd8cxKXPkF+lpYE=,tag:RaJ3ztrNkNRAiWaByNCsRQ==,type:str]",
		"version": "3.12.1"
	}
}