{
	"data": "ENC[AES256_GCM,data:+/OouALFNH4bzjGynfFJeUXFFWKx9Dd0NeX4ASx1+ygR1ZXR4RR1nPqbjqlOd8fJ8tPYsko3GyWqDCEDDa2GtjiUQ7QPJDXN4y9ZjEBfilbkKWuB/743tLdQZ6+cIJyK61UAn8LAW61y6dtCfudJw2soycrL1EvER1uUhI0JilaD6ZvsiUsm4G/cM/dVq+YwTKtMDEvvf5lQ+bmxF0sLFqoEfYd56urgZ32hhKCTIxqC0h0/GH4c5i8wcRJN3EwbP6JoDa68GdHsC0p+e2GGP5KPPkXm1cgSbqcXg4n8vRbcu9IjwyMJZGZGesmR6nE1kO8tDArBWnHcfCpQ0WrHeniui8QorLVSea4QA9+g0WxHhyYIAVIfYmKPNp0pSYc7QRAskwGnE610kBDkohwz04Pt1twRJBgJH/UdEPZNrYeJ5HBNDUqb2pDvnpiUdsXvKtIY3GiITs3lWMM9Swo90J1mQOizdI2eS8WwTcs9nBLR7eK9ckkXXakaiBhCLzqAtfWjWLSSpXKtpW54YGGgQjHV4szTnFuCEu3tnQnmKAV8DaVyJ96Y5AVoQGFU9p1ZqOrIobZdSTNZYzks486mXfZjBbs58QSDmxcZk3NhD5QKWSSPx0TMU5ann34RqevFuMl39Vg=,iv:y9q6xB2vlq4ai7hP/Tz1y3kADkv3nUxYuwuKYo7XMIQ=,tag:BRALLLbiJ8f3K340nUNM6Q==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1cnktwwj4lq4lm5qa3vxn2ft5n38h557smr2f58t9vz4zum5w0udqzzle6c",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJc0VuZGpuSU9ndjR1MlRl\neVFzMllOODRGeG5iQzczaGsrc29GK1Vvc3lrCkVOSzJpSllCcVVrdkN6eklEeVlu\nZ2MySXNkcU9HQzljVVViaUtrZFp4MncKLS0tIHhlbHNZUmZLTzJzYytERjZPbjN1\nWU9aeUhvRytSUlBVUEg0ZVhRcUJNQVEKPC3Ygki614bNXlxZWSjk1/yvqPCeGD+y\n8bJsDeeqyMdEPM+neyntlKy9Whau80aX7qO+Mn7CkJpnlz4t4ngLxA==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-04-19T08:48:13Z",
		"mac": "ENC[AES256_GCM,data:1wD1LMf7311V22/as2CzepxLUi0egq8GjDog1s98O9iSWbtaIAlSCNBlXcP1YEuA69dtbBlHIulep72seaO43AlqomuhWUHTG/liIoqRh/vzQqhtnSAh2iA9nzFVxWGYRk8tTrQrfZk8RzWq9iLNeNvZ1/z5js7BZp5wLcvtK48=,iv:dzTvYFZ1Aww1fXJU1XfEiy7bmuCae4iSBuSUK+8+xaE=,tag:tt5eaH49SVzZ3jInCHEU7w==,type:str]",
		"version": "3.12.1"
	}
}