{
	"data": "ENC[AES256_GCM,data:XOQkwzXrOulk+k2k0n9OiFGkzF/8C14Ezl/k2o3ERcJ/mrD0jd+Ed7+D2q1D8LRUZBRH+FcqM9Bvh2rMTpoH1nAojjCGMCX5/zFVnasU4OOAjfV2jA04oEvcPvV2vt2pOA20S8ZS3ZZRx1Jf/LiaKGjWvuFM6dk6Ri/ZgbMGceMQm9NR9gbyTfiupZNBlnbUkSZb7oYt9W+1LWomW7zVuTVVsb9VBXbRiYjFcUhWcrWh6s2hK4WpUKOMdRzz5UK8qMFkiMPq6J0WqyAJf3I9vf7cgHqCLOku9fSbwHr3mb3ZWz2I35yN2AYSFvJwgXy8sf6nNvgI+yhLJDHPtwHtZdJug8ytdyMVWXmI,iv:v/M2T3aA6qEVVDJEFFBwgM/cCZJQanh7bCm3eCxCq1E=,tag:pxralrTMONgGHliIFsbmKA==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1cnktwwj4lq4lm5qa3vxn2ft5n38h557smr2f58t9vz4zum5w0udqzzle6c",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxUm4vanlSaStHMkZ4Ym9Q\nRlNpWlB1S3hVU0IwbHdyOVJDZ3V6SUhkZ0N3Clphak5Sb1dOWXVOaGNaS2FjSzhV\nY3BZbmozNEF1cmFKZnFsdWxjanMwZGcKLS0tIEUxRWJYeEZuUGJpWmZpeldIMFY4\nSHBONWl5dHk0MTlhWWdsYlVsUjl4V0EKPHnIYOEmnUrPRxs/Y9SrH422Gdw90KWJ\n7+opn+WHHu1W2GGcE54xsGhQJwlPJoV7WC02PdvYiPTdE0ClpfyVcw==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-04-16T07:02:17Z",
		"mac": "ENC[AES256_GCM,data:YRmdybPcWyTqvK80ZeLRCQXzuYfh8UIWqzV87QGK5Xq9zQlrk4vhFClBY5Nysts16GSBvhdMFLnob5SyPRJXKHf0Xq8YLYNEEMYFCPqY5qClZ2NlCkZ1MjV8kSy09rzh5Fi0ZSJmO/ELXlc71yqQyiQVcuxjfOUEfn0yiGOMaio=,iv:LWLn+LgxS5LLgmAvoejwTZOvm/rof44mfg3FXWeJo34=,tag:aGNP3MQzeGxXpbbx0T1Hmg==,type:str]",
		"version": "3.12.1"
	}
}