{
	"data": "ENC[AES256_GCM,data:0ertR+5BCtmsvF8ygyxvgNFvL0aw47Z7MYFc3STOUNaPhHXCLtvOKSA/8PDxQ/vyGkK2mtZfTjLU+Po+zwUh8/SvgWlzyjbvofLozMQuhab0QfYgwW3AncyFDBz88SJdYHG8eA5WTnOj9R2YY2VtvVnGHS1VHTypeLiSgxh0ZKxTBfI9P+wwa0ar6unU7CfDkC2pIWCTmy1DfqWhbJoYjv/g9mtfykttPKBTfLGXkdwLBGo84+FMPzZz6H2Fy+QSjmyqWEkaDFuYoKkYRfjkkVXRjwA=,iv:2SqYGg3l0y9FM7xhN0QehWcuzxGqxCm5GSNV7ArQwvI=,tag:QpUjMQCqAtEVipteZeSDUQ==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1cnktwwj4lq4lm5qa3vxn2ft5n38h557smr2f58t9vz4zum5w0udqzzle6c",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3T25YaStwNjJLd2UyUjQ4\nU1R3MldzVnRiUzhCODM0Ukt4Z2YwVlQrMEZjCloyYjF1aUJLOUdHbDlBbTNDUURJ\naGt1ekMwOG1yQWU5WlpvOG01OXE3VjAKLS0tIFZGc0d0MjFwNVhXcWpyMnQ0VUNU\nZWNBUmFWZzdtTTh3VVNuQ3Q1djNZNGcK8h9zRgN+DIFWBdX4Qc8fTN5aJ5G/US/o\nL9xEvGTjbVjTnvRvNWRhzPgiHxsajv8WXSI0wh/Zn1J+3bhf4EwXyg==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-04-19T06:23:38Z",
		"mac": "ENC[AES256_GCM,data:SqXEvQmbTQFO4PFqf1SVPvm7cYwbMkauL9mlXXlf+uri5rxnqlqvtXcAuhuSOT5Mgi+XnEOlAHvUC2VyXq9jb2Wn6R7ya4MAxQ7vc0lodyMva6pdECIN52En8IQ9NxJ6aF10gZGJf+WeVw8P/cgJMBlDa8cZ9/KzDELAAwAZMfU=,iv:Cx5tHL0xdKpvBhqx4mEsvdIMjt9FzI/K2a2CQefnBdo=,tag:WnCuS+xeJqMpL7o8HHXR7Q==,type:str]",
		"version": "3.12.1"
	}
}