{
	"data": "ENC[AES256_GCM,data:4z3fBOAyrRBtkoNEjFp7rTH13jwZ3niel6jy1wgNoBovk1AgWdgWC6C6WmkNAueJT9JRZlRC8ES2vacSiDy+6i7ThducKVpF5Gw8/R+sc6cAVIz6djajnWJz+c/S3DLVHi4KCW/cHHslMNw2NzpBKynBxfcr7yQKOvd869//pOyvAa/hF/RTZhswxgwDWQqNsdCtV2BQmrO0Cc59zmP9SHb8wwf4oyzIivNKPS94F+kw9d/deoqtcxmTpmsKUTg15qWcOKD+DSKst4G7DNujntbzhec=,iv:Z0mwOaU5yd097+7/9it+hFpAM02xRC9Z++l0587QBTY=,tag:CBp2cRapMm15NkA4ivbG6w==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1cnktwwj4lq4lm5qa3vxn2ft5n38h557smr2f58t9vz4zum5w0udqzzle6c",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBITXAxcXByRTVBeGNXbzNm\nUThTVkxrOFV3VHpUbEl5Mm9JTGNDTTlISFJVClBiUmhQTnRKQTVucnZFMWprNWlr\nakpmNEZQSkhqMlBBTHpEekNTVmRvK2MKLS0tIEdrNDZQMm1qczl5NW40UmFwYUth\nblh5dWtDNEJpTnM5YXhIR0lFbmZlSFUK6UnlfM/uvuCFrr4UWVzewkSHtfyCItaV\nfFalUpdZxkd4SDQ04HQeYaaYbSonoHUSO0/ecHJdyAVwavB3nvy4ow==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-04-20T01:04:16Z",
		"mac": "ENC[AES256_GCM,data:jUi8iC+UjQxcFY1ZIM8SQ4eTk+lNk+Dk5q6SwY3N/Rc8i6LlKRcqrKAPDSJOL+bVUNAz13Ob/F2ZRudDggFVEE8mSN7dERBYKbkt9dXTBv4pOGnFzhJD8LvXSI1lKynfrC8aAfvzoN8NWEaYsCsyqoTTmip3YQ1p3Jpf5ednnCE=,iv:nl7vOKHGRqu+8E4byKq0MJgHmmcljtnvLhvSorqAJXk=,tag:Ls96Y7j20XBUQwTOSaNxUw==,type:str]",
		"version": "3.12.1"
	}
}