{
	"data": "ENC[AES256_GCM,data:SF7Fg35dOnLUy7v1UQF3Rreflr2JCNNuIlodUUSVIQ/Xl2avwOu2JhEfQYtNVaLwob1TFUGCOlurb5iz9nAqmfbeGZH9ThzccCUHQ5Druqk3zAZNK/6pgkvH4BzKNGPtaxdRq+iM/hEROwcI0fTltQ9aw9phoav5bGTM0FI0Ar6lJbW2lfIXsxGc2THzcurHooL1Lbu5UiIunTohAjYypu8d3WaGfuJxiGVEnyPBXZaAA/BZU/Jxe3ErmA==,iv:PB+50miBuKlD9/ZaM6FZiDwLRgR//UGVdcMJeI+oIEc=,tag:i2+Kx5qKxZJG+kVAa1sKrQ==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1cnktwwj4lq4lm5qa3vxn2ft5n38h557smr2f58t9vz4zum5w0udqzzle6c",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvZmpGcE1VQjJ3VkxFemlR\nZ1lDVjh6NnF0bEVIWGpka2ZSYXZhbmI4Wkh3CjJNQkdhTjIxUTFjMW9uVUZlRXhr\nc1NwaEpWblpwSTh5NzhQMUp6U29senMKLS0tIGVITTNQcnErY01tYnVianpKcGJx\nVG9mOUFnUEhIdkxvb2NsTFp4T0JpemcKJwblYHEsZw5EkVHRReySy2IZ7Ao2I39e\nUvUA9c0u8rbrBDr0cdhgbVuApytVUqAxW56jXK1kFaAu0Apbi0XYyQ==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-04-22T05:19:15Z",
		"mac": "ENC[AES256_GCM,data:PmwLacwJt7ib/rhQK07Q2Zy1zkEBN6xeh/XKlqneQEceQSXT73SKRcUjc+ZvAywGgwVd9MF44K5zLshL710fbp9aeClsv4ezwHiaXPOfmitNOuwbN+JLJQYWNL1/Cgk3REu58XFusGN0YxZ2t+sxSc2MLMv4jnHVRZtP9NhslRk=,iv:ISVfMMJkDqqY43F3YTt6cupy06zPxL1H9FwSnuCS2Qc=,tag:qc3d0AMR1kwErSF48lhnRA==,type:str]",
		"version": "3.12.2"
	}
}