{
	"data": "ENC[AES256_GCM,data:FCE8WzpRF5se92hPewZEnXEzWOSCD9toevHTiluoGM8jwjOMfP7OZSTuc3JJt6MXeTYoNLFDCUntV74QQKZxD3i7xYSH8KU2E//995TeHW6JU5ehX30R/O6uFIO4Va90e0c4ct8DHnZ5tjjtM6RTP4P2Gev8UIe8gXoBv6OMsVtpgGCWH/ArekyQCgTsm/JkyiActHTJ6ks9Qjq9CqVV3iWLXE055jR3UkIn+b8yJlT1k+ze02aQr5hhRg==,iv:VF0tl1NUuSmjNWapFllpX5HCc+fybZJID88LBe41ucU=,tag:f24VeefRQgCS9bPCKu2BMA==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1cnktwwj4lq4lm5qa3vxn2ft5n38h557smr2f58t9vz4zum5w0udqzzle6c",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZTmF3SlhkaXVZV1A3TTI3\nUnpWTGVpM2tlMjJ0OXFiWGVtTWpqc1hLQWlFCjNiN3VsN0ozN2RVNjFpemRnZVc2\nOTY1cGtWbW1PaHZGaEl2bXJlWXliVGsKLS0tIE0xTnVCVHpnZDVuR2tjeTBIalNQ\nYlppRTBjNjN1NXAvb0lZN0JQOVNjWUUK50jbMJgW+Ol5fzOcILO0sDnVmgqbw+ap\nfxH0THbJ/hGGkrp+OC72ZBfqR96u2bXvQmWk/nVioNbaVcwH/fE08w==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-05-04T06:07:13Z",
		"mac": "ENC[AES256_GCM,data:L3n6i1DKnWeQw2HxB6FzjBR29O0XyZ9JH8zJR3c0NenVnU4wWY4NwUBCPcb+EG+FDcWXYQssEKKG17wTmOwcDtvmbwmD62YFWQM8YgJnLmVhS9xja1Ci7NTgZ+oYXOoPkuWGwCijBJmry3ClRfZ4xt9SrSn+/yJPVqAjpV0jFdY=,iv:TbE/IpFT6+yxqQEPoLimF06Lne8E3p2/isWs/5UOCMA=,tag:9p3RNz6nhxbBAmuu/tIQAA==,type:str]",
		"version": "3.12.2"
	}
}