{
	"data": "ENC[AES256_GCM,data:K/r+4jYNmyOlyDRFCtlrzMbFLupid7CDHPQJTZ6gMVeEgZMXBH/qv1vVoB7EC15M2Wd9bnD5hec7DC/kk2Uq12vPIfBYllivkedZykiRchX6s1aJ8fTdPhBLOzmP3EVfZk9Wt/NniJfXVGt1YIAGcbkjRDAOe8125YrPdKQwKgUKkUOOPfy+7y8E/tBMtOnQ/o4gIZ0AG2aB1pWOGz2hhovCcY0VgvFQ2mcV4s8Jz7su/pYLvpdHGNVN,iv:oOjvV/0DwTKv9DGMIpcXpXVES3G8qx5IqXn3lEedFWE=,tag:DhXhFrHj7BrZH7baAxqpJQ==,type:str]",
	"sops": {
		"age": [
			{
				"recipient": "age1cnktwwj4lq4lm5qa3vxn2ft5n38h557smr2f58t9vz4zum5w0udqzzle6c",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTGFKdVVwendqb09ibDlx\nMkNRdytxY1U0cVp5N2xHaHl3UUZObTZ5V3lnCnJrcHZpTUh6RU5UYmdZQS9laDFx\nMStHV0NVUkxKd0lybUV4NHJTUlM0NTQKLS0tIFhTODU4SGtJK3B6aStTS1VrcWZa\nemhCQlRRZlU0WTlaTFlxM0lJTmI2dFkKRz6AnF/GTAyuBogv2aYQqFEDdh3mQJ+k\nvIxdPVAxpAzxf8Y8Ym+nOUHNoWW88zjIXaR9me3uuzFq+w0FzmpOyQ==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2026-04-15T02:53:45Z",
		"mac": "ENC[AES256_GCM,data:uh+TerpmL3mv7hrI7Z8pLfucBGmgPbYOrf/20y2qR194wNg05TOpt20z7HYFJcZd3GYXCSfG9JMfBc9S6XWuVQ/U7Zbzp+MVQmvji6xQm/KVx0e1jJ0l8z48lfzUGASXOGU2nUao8iYTJIzEhZOER30ypD0lkg5ddRhdVNwa3Fc=,iv:sw5EyODNsGkuVqIPHb/ydxyM9IJNJNK2JJSjaNCa0HA=,tag:U2XAIqQ7TWK4uHWnwjNqjg==,type:str]",
		"version": "3.12.1"
	}
}